# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: bsgrigorov/zensical-example
  branch: main

media_folder: docs/images
public_folder: images

collections:
  - name: pages
    label: Pages
    folder: docs
    create: true
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: showcase
    label: Showcase
    folder: docs/showcase
    create: true
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
